* Schedule
- On the 1st, of February the testing scenarios, methodology etc. should be agreed upon - it should be written before 1st, but there is no time to agree on it in the first week of the month due to time constraints.
- In the first (if second, we might have trouble) week of February a pilot testing should be done - preferred subjects - Vojtěch Polášek and someone with Windows (very likely most of them will use that OS)
- Main testing should occur in February, first week of March might be acceptable
* General notes
- Subjects - visually impaired people - blind are preferred over partially sighted, they should be at least somewhat capable with a computer (the entry bar for the Linux group is currently much higher as the install is not straight-forward in any way)
- Very likely a Jitsi meet call (thanks, Covid-19).
- General objective - find out how the people rate the usability, usefulness of the application and gather suggestions for future development
* Plan
** Before meeting
- The subject will get the user docs (including download links and the scenarios)
- He'll be encouraged to try the scenarios and whatever he sees fit
- The participants will have at least a week of time for their own testing and possible questions (hopefully no new bugs will be found during this period)
- Will know about the meeting and its future recording and the recording's deletion timeframe and related things
** The meeting
- Duration approx. one hour
- Very likely a Jitsi meet call, preferrably with Chromium based browser so we can have a recording of the computer audio as well
- The participant will be asked about the confirmation of recording the interview - if declined, the meeting will continue nonetheless, but writing actionable notes might prove somewhat harder
- The general structure of the meeting will be explained
- Some initial questions will be asked
  - General classification of their visual impairment - completely blind/partially sighted or something like that
  - How would you rate your computer skills
  - Did you use similar apps (desktop/mobile) and how often/how?
  - A rough age classification (not sure whether the subjects are age diverse enough so this metric matters)
*** Part I
- The participant will be asked about their opinions after the free testing
- No specific 	questions will be asked yet
*** Part II - Application explanation, basic testing scenarios
- A basic explanation of the app
- Will explain basic concepts - area selection, walking, near by queries, simple search etc.
- The scenario from the user docs will be used for demonstration purposes
- If the first part indicates that the participant used the app enough, this part might be skipped entirely
*** Part III
- The participant will be asked whether he wants to try anything he did not try during the week, ask any questions etc.
- Might be skipped if the participant looks like he didn't test anything, e. g. has no experiences with the app and don't seems to be as big a tinkerer
- Of course if he provides all the feedback in the first or second part, this might be skipped as well
*** The questions
- They might be answered during the interview - or at least some of them
- Will try to quantify the learnability, efficiency, memorability, number of error conditions and user satisfaction
- These will not have a numeric answer for the survey data
- After the specific area questions, the System usability scale will be used to evaluate the application as a whole
**** Areas of interest for the area specific questions
- Area selection
- New area request UI
- Main window - including the menu structure, shortcuts, walking behaviors etc.
- The near by objects dialog + the actions on objects
- The search UI